### ISSUE TITLE
about HDR data processing during training

### ISSUE THREAD

**Issue by sunyclj** [mukulkhanna/FHDR#13]
Hi,LDR data is of type UNIT8 and normalized to [-1,1]，HDR data is of type Float32,if you follow the code, HDR data is not normalized to [-1,1],the  value of hdr_tensor is greater than 1 ,the loss value will occur nan.The HDR data processing code is as follows:

transform_list = [
            transforms.Lambda(lambda img: torch.from_numpy(img.transpose((2, 0, 1)))),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),  
        ]
transform_hdr = transforms.Compose(transform_list)
hdr_tensor = transform_hdr(new_hdr)

How can WE effectively normalize HDR data value to [-1,1]?

**Comment by mukulkhanna** [comment]
Hi @sunyclj,

Yes we aren't normalizing the ground truth (GT) HDR in the data loader. Its range is [0,inf] when it comes out of the data-loader. And that's okay because the GT HDR image doesn't go into the network. The GT HDR image is used for computing the loss when the network's prediction (from the LDR image) comes out.

We normalize the GT HDR image and the network's prediction both to [0,1] before we compute the loss between them ([here](https://github.com/mukulkhanna/FHDR/blob/01a21e760c1c38e82a9a49885cb4dbe5f7754045/train.py#L135-L140)).

This normalization is done using the mu-law tonemapping function (more info in the paper) implemented [here](https://github.com/mukulkhanna/FHDR/blob/01a21e760c1c38e82a9a49885cb4dbe5f7754045/util.py#L32).

**Comment by sunyclj** [comment]
@mukulkhanna ok,thank you. please, where is the code to calculate Q-score?  I don't find.

**Comment by mukulkhanna** [comment]
We calculate the Q-score using the HDRVDP-2 (MATLAB) codebase. You can find more information about their project and source code here: 

- http://hdrvdp.sourceforge.net/wiki/  
- https://sourceforge.net/projects/hdrvdp/files/hdrvdp/
